### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269** [hashgraph/hedera-exchange-rate-tool#215]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by PavelSBorisov** [comment]
No CODEOWNERS file

**Comment by andrewb1269** [comment]
The groups here should be:

@hashgraph/devops-ci
@hashgraph/release-engineering-managers
@hashgraph/hedera-services 

We should add .github/CODEOWNERS and include the catchall rule and the standard core rules.

**Comment by PavelSBorisov** [comment]
Closing PR and issue as repo isn't updated regularly, as discussed with @rbarkerSL and @andrewb1269hg
